"""remove item

Revision ID: 015541ec945a
Revises: a48a7c70efc6
Create Date: 2026-05-19 19:48:46.243650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '015541ec945a'
down_revision: Union[str, None] = 'a48a7c70efc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'health_assessment', ['id'])
    op.create_unique_constraint(None, 'risk_assessment_result', ['id'])
    op.create_unique_constraint(None, 'user_profile', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_profile', type_='unique')
    op.drop_constraint(None, 'risk_assessment_result', type_='unique')
    op.drop_constraint(None, 'health_assessment', type_='unique')
    # ### end Alembic commands ###
