"""add health data and prescription

Revision ID: 32920df4cfda
Revises: b389592974f8
Create Date: 2026-03-24 01:08:21.471161

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "32920df4cfda"
down_revision: Union[str, None] = "b389592974f8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("items_user_id_fkey", "items", type_="foreignkey")
    op.drop_column("items", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "items", sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.create_foreign_key("items_user_id_fkey", "items", "user", ["user_id"], ["id"])
    # ### end Alembic commands ###
