"""added clinician model appointments etc

Revision ID: 3e424707d4a3
Revises: 5ff96d488f46
Create Date: 2026-05-29 22:24:09.357061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '3e424707d4a3'
down_revision: Union[str, None] = '5ff96d488f46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinician_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('middle_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('specialization', sa.String(), nullable=False),
    sa.Column('license_number', sa.String(), nullable=False),
    sa.Column('hospital_name', sa.String(), nullable=True),
    sa.Column('years_of_experience', sa.Integer(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_clinician_profiles_slug'), 'clinician_profiles', ['slug'], unique=True)
    op.create_table('appointments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('clinician_profile_id', sa.UUID(), nullable=False),
    sa.Column('appointment_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('clinician_notes', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'COMPLETED', 'CANCELLED', 'MISSED', name='appointmentstatus'), nullable=False),
    sa.Column('is_virtual', sa.Boolean(), nullable=True),
    sa.Column('meeting_link', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['clinician_profile_id'], ['clinician_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clinician_patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('clinician_profile_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'DISCHARGED', name='clinicianpatientstatus'), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clinician_profile_id'], ['clinician_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('clinician_profile_id', 'patient_id', name='uq_clinician_patient'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_clinician_patients_clinician_profile_id'), 'clinician_patients', ['clinician_profile_id'], unique=False)
    op.create_index(op.f('ix_clinician_patients_patient_id'), 'clinician_patients', ['patient_id'], unique=False)
    op.create_unique_constraint(None, 'risk_assessment_explainability', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'risk_assessment_explainability', type_='unique')
    op.drop_index(op.f('ix_clinician_patients_patient_id'), table_name='clinician_patients')
    op.drop_index(op.f('ix_clinician_patients_clinician_profile_id'), table_name='clinician_patients')
    op.drop_table('clinician_patients')
    op.drop_table('appointments')
    op.drop_index(op.f('ix_clinician_profiles_slug'), table_name='clinician_profiles')
    op.drop_table('clinician_profiles')
    # ### end Alembic commands ###
