"""updated user prescription relationship 

Revision ID: 5be8ef34e951
Revises: fd722750b736
Create Date: 2026-06-09 13:09:22.799445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '5be8ef34e951'
down_revision: Union[str, None] = 'fd722750b736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'prescriptions', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'prescriptions', type_='unique')
    # ### end Alembic commands ###
