""" add unique to user_id

Revision ID: 5f14235dbd22
Revises: eb812596c210
Create Date: 2026-04-02 11:38:30.828898

"""
from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "5f14235dbd22"
down_revision: Union[str, None] = "eb812596c210"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "user_profile", ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_profile", type_="unique")
    # ### end Alembic commands ###
