"""add explainability model

Revision ID: 5ff96d488f46
Revises: af4f4c83c9f1
Create Date: 2026-05-26 13:54:24.404574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "5ff96d488f46"
down_revision: Union[str, None] = "af4f4c83c9f1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "risk_assessment_explainability",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("risk_assessment_id", sa.UUID(), nullable=False),
        sa.Column("top_risk_factors", sa.Text(), nullable=True),
        sa.Column("recommendation", sa.Text(), nullable=True),
        sa.Column("clinical_summary", sa.Text(), nullable=True),
        sa.Column("shap_values", sa.Text(), nullable=True),
        sa.Column("lime_explanation", sa.Text(), nullable=True),
        sa.Column("inference_time_ms", sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(
            ["risk_assessment_id"], ["risk_assessment_result.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("risk_assessment_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("risk_assessment_explainability")
    # ### end Alembic commands ###
