"""updated relationships

Revision ID: 60f2d44a0f17
Revises: 664c6684fbea
Create Date: 2026-05-20 12:11:54.964213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "60f2d44a0f17"
down_revision: Union[str, None] = "664c6684fbea"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "health_assessment_profile_id_fkey", "health_assessment", type_="foreignkey"
    )
    op.drop_column("health_assessment", "profile_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "health_assessment",
        sa.Column("profile_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "health_assessment_profile_id_fkey",
        "health_assessment",
        "user_profile",
        ["profile_id"],
        ["id"],
    )
    # ### end Alembic commands ###
