"""add user id to healthassesment

Revision ID: 664c6684fbea
Revises: 015541ec945a
Create Date: 2026-05-19 20:45:43.638757

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '664c6684fbea'
down_revision: Union[str, None] = '015541ec945a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_assessment', sa.Column('user_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'health_assessment', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'health_assessment', type_='foreignkey')
    op.drop_column('health_assessment', 'user_id')
    # ### end Alembic commands ###
