""" User profile model

Revision ID: 7ea068d30ded
Revises: 77a5ca1a5c2c
Create Date: 2026-04-01 16:40:12.063973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7ea068d30ded"
down_revision: Union[str, None] = "77a5ca1a5c2c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_profile",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column(
            "sex", sa.Enum("male", "female", "other", name="gender"), nullable=False
        ),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("height", sa.Float(), nullable=True),
        sa.Column("bmi", sa.Float(), nullable=True),
        sa.Column("smoking", sa.Boolean(), nullable=False),
        sa.Column("diabetes", sa.Boolean(), nullable=False),
        sa.Column("history_cvd", sa.Boolean(), nullable=False),
        sa.Column("kidney_disease", sa.Boolean(), nullable=False),
        sa.Column("family_history_htn", sa.Boolean(), nullable=True),
        sa.Column("on_bp_medication", sa.Boolean(), nullable=False),
        sa.Column("total_cholesterol", sa.Float(), nullable=True),
        sa.Column("hdl_cholesterol", sa.Float(), nullable=True),
        sa.Column("glucose", sa.Float(), nullable=True),
        sa.Column("physical_activity_level", sa.String(), nullable=True),
        sa.Column("diet_quality", sa.String(), nullable=True),
        sa.Column("alcohol_use", sa.Boolean(), nullable=True),
        sa.Column("stress_level", sa.String(), nullable=True),
        sa.Column("sleep_quality", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_profile")
    # ### end Alembic commands ###
