"""initial schema

Revision ID: a48a7c70efc6
Revises: 
Create Date: 2026-05-19 19:38:33.260983

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "a48a7c70efc6"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "prescription",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("medication_name", sa.String(), nullable=False),
        sa.Column(
            "route",
            sa.Enum(
                "oral",
                "iv",
                "subcutaneous",
                "intramuscular",
                "transdermal",
                name="administrationroute",
            ),
            nullable=False,
        ),
        sa.Column("prescription_trigger", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "user_profile",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("first_name", sa.String(length=50), nullable=False),
        sa.Column("middle_name", sa.String(length=50), nullable=True),
        sa.Column("last_name", sa.String(length=50), nullable=False),
        sa.Column("phone_number", sa.String(), nullable=True),
        sa.Column("date_of_birth", sa.Date(), nullable=False),
        sa.Column(
            "sex", sa.Enum("male", "female", "other", name="gender"), nullable=False
        ),
        sa.Column("work_type", sa.String(), nullable=True),
        sa.Column(
            "education",
            sa.Enum(
                "PRIMARY", "HIGH_SCHOOL", "UNDERGRAD", "GRADUATE", name="educationlevel"
            ),
            nullable=False,
        ),
        sa.Column("diabetes", sa.Boolean(), nullable=False),
        sa.Column("heart_disease", sa.Boolean(), nullable=False),
        sa.Column("history_cvd", sa.Boolean(), nullable=False),
        sa.Column("kidney_disease", sa.Boolean(), nullable=False),
        sa.Column("prevalent_stroke", sa.Boolean(), nullable=False),
        sa.Column("prevalent_hypertension", sa.Boolean(), nullable=False),
        sa.Column("family_history_htn", sa.Boolean(), nullable=True),
        sa.Column("family_history_cvd", sa.Boolean(), nullable=True),
        sa.Column(
            "smoking",
            sa.Enum(
                "never",
                "former",
                "passive",
                "current_light",
                "current_heavy",
                name="smokingstatus",
            ),
            nullable=False,
        ),
        sa.Column("cigs_per_day", sa.Integer(), nullable=True),
        sa.Column(
            "alcohol_use",
            sa.Enum("none", "moderate", "heavy", name="alcoholuse"),
            nullable=True,
        ),
        sa.Column(
            "physical_activity_level",
            sa.Enum("NONE", "LOW", "MODERATE", "HIGH", name="physicalactivity"),
            nullable=True,
        ),
        sa.Column("exercise_frequency", sa.String(), nullable=True),
        sa.Column("diet_quality", sa.String(), nullable=True),
        sa.Column("salt_intake", sa.Float(), nullable=True),
        sa.Column("stress_score", sa.Integer(), nullable=True),
        sa.Column("sleep_duration", sa.Float(), nullable=True),
        sa.Column("sleep_quality", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "dose_schedule",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prescription_id", sa.Integer(), nullable=False),
        sa.Column("dose_duration_value", sa.Float(), nullable=True),
        sa.Column("dose_duration_unit", sa.String(), nullable=True),
        sa.Column("dose_administration_duration_value", sa.Float(), nullable=True),
        sa.Column("dose_administration_duration_unit", sa.String(), nullable=True),
        sa.Column("dose_value", sa.Float(), nullable=True),
        sa.Column("dose_unit", sa.String(), nullable=True),
        sa.Column("dose_min_value", sa.Float(), nullable=True),
        sa.Column("dose_max_value", sa.Float(), nullable=True),
        sa.Column("frequency", sa.String(), nullable=True),
        sa.Column("dose_prn_trigger", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["prescription_id"],
            ["prescription.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "health_assessment",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("weight", sa.Float(), nullable=True),
        sa.Column("height", sa.Float(), nullable=True),
        sa.Column("bmi", sa.Float(), nullable=True),
        sa.Column("log_bmi", sa.Float(), nullable=True),
        sa.Column("glucose", sa.Float(), nullable=True),
        sa.Column("avg_glucose_level", sa.Float(), nullable=True),
        sa.Column("total_cholesterol", sa.Float(), nullable=True),
        sa.Column("hdl_cholesterol", sa.Float(), nullable=True),
        sa.Column("on_bp_medication", sa.Boolean(), nullable=False),
        sa.Column(
            "smoking_status",
            sa.Enum(
                "never",
                "former",
                "passive",
                "current_light",
                "current_heavy",
                name="smokingstatus",
            ),
            nullable=True,
        ),
        sa.Column(
            "alcohol_use",
            sa.Enum("none", "moderate", "heavy", name="alcoholuse"),
            nullable=True,
        ),
        sa.Column(
            "physical_activity_level",
            sa.Enum("NONE", "LOW", "MODERATE", "HIGH", name="physicalactivity"),
            nullable=True,
        ),
        sa.Column("assessment_notes", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["user_profile.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "blood_pressure",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("assessment_id", sa.UUID(), nullable=True),
        sa.Column("systolic_value", sa.Float(), nullable=False),
        sa.Column("diastolic_value", sa.Float(), nullable=False),
        sa.Column(
            "systolic_unit", sa.Enum("mmHg", name="bloodpressureunit"), nullable=True
        ),
        sa.Column(
            "diastolic_unit", sa.Enum("mmHg", name="bloodpressureunit"), nullable=True
        ),
        sa.Column("pulse_pressure", sa.Float(), nullable=True),
        sa.Column("start_date_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "descriptive_statistic",
            sa.Enum("average", "maximum", "minimum", name="descriptivestatistic"),
            nullable=True,
        ),
        sa.Column(
            "temporal_relationship_to_physical_activity",
            sa.Enum(
                "before_exercise",
                "after_exercise",
                "during_exercise",
                "at_rest",
                name="temporalrelationship",
            ),
            nullable=True,
        ),
        sa.Column(
            "temporal_relationship_to_sleep",
            sa.Enum(
                "before_sleep",
                "during_sleep",
                "after_sleep",
                name="temporalrelationshiptosleep",
            ),
            nullable=True,
        ),
        sa.Column(
            "body_posture",
            sa.Enum("sitting", "standing", "lying", "reclining", name="bodyposture"),
            nullable=True,
        ),
        sa.Column(
            "measurement_location",
            sa.Enum(
                "left_wrist",
                "right_wrist",
                "left_arm",
                "right_arm",
                name="measurementlocation",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["health_assessment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "heart_rate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("assessment_id", sa.UUID(), nullable=True),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column(
            "unit", sa.Enum("beats_per_min", name="heartrateunit"), nullable=True
        ),
        sa.Column("start_date_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "descriptive_statistic",
            sa.Enum("average", "maximum", "minimum", name="descriptivestatistic"),
            nullable=True,
        ),
        sa.Column(
            "temporal_relationship_to_physical_activity",
            sa.Enum(
                "before_exercise",
                "after_exercise",
                "during_exercise",
                "at_rest",
                name="temporalrelationship",
            ),
            nullable=True,
        ),
        sa.Column(
            "temporal_relationship_to_sleep",
            sa.Enum(
                "before_sleep",
                "during_sleep",
                "after_sleep",
                name="temporalrelationshiptosleep",
            ),
            nullable=True,
        ),
        sa.Column(
            "body_posture",
            sa.Enum("sitting", "standing", "lying", "reclining", name="bodyposture"),
            nullable=True,
        ),
        sa.Column(
            "measurement_location",
            sa.Enum(
                "left_wrist",
                "right_wrist",
                "left_arm",
                "right_arm",
                name="measurementlocation",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["health_assessment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "risk_assessment_result",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("profile_id", sa.UUID(), nullable=False),
        sa.Column("assessment_id", sa.UUID(), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column(
            "disease_type",
            sa.Enum("CHD", "STROKE", "HYPERTENSION", "CVD", name="diseasetype"),
            nullable=False,
        ),
        sa.Column("model_version", sa.String(length=50), nullable=True),
        sa.Column("risk_probability", sa.Float(), nullable=False),
        sa.Column("risk_percentage", sa.Float(), nullable=False),
        sa.Column(
            "risk_level",
            sa.Enum("LOW", "MODERATE", "HIGH", "CRITICAL", name="risklevel"),
            nullable=False,
        ),
        sa.Column("prediction_label", sa.Boolean(), nullable=False),
        sa.Column("top_risk_factors", sa.Text(), nullable=True),
        sa.Column("recommendation", sa.Text(), nullable=True),
        sa.Column("clinical_summary", sa.Text(), nullable=True),
        sa.Column("shap_values", sa.Text(), nullable=True),
        sa.Column("lime_explanation", sa.Text(), nullable=True),
        sa.Column("inference_time_ms", sa.Float(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["assessment_id"],
            ["health_assessment.id"],
        ),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["user_profile.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("risk_assessment_result")
    op.drop_table("heart_rate")
    op.drop_table("blood_pressure")
    op.drop_table("health_assessment")
    op.drop_table("dose_schedule")
    op.drop_table("user_profile")
    op.drop_table("prescription")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
