"""init health data

Revision ID: a98f77fdd011
Revises: 6b229e3db394
Create Date: 2026-03-24 15:31:53.936178

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "a98f77fdd011"
down_revision: Union[str, None] = "6b229e3db394"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bloodpressure",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("unit", sa.String(), nullable=True),
        sa.Column("start_date_time", sa.DateTime(), nullable=False),
        sa.Column("end_date_time", sa.DateTime(), nullable=True),
        sa.Column(
            "descriptive_statistic",
            sa.Enum("average", "maximum", "minimum", name="descriptivestatistic"),
            nullable=True,
        ),
        sa.Column(
            "temporal_relationship_to_physical_activity",
            sa.Enum(
                "before_exercise",
                "after_exercise",
                "during_exercise",
                "at_rest",
                name="temporalrelationship",
            ),
            nullable=True,
        ),
        sa.Column(
            "temporal_relationship_to_sleep",
            sa.Enum(
                "before_sleep",
                "during_sleep",
                "after_sleep",
                name="temporalrelationshiptosleep",
            ),
            nullable=True,
        ),
        sa.Column(
            "body_posture",
            sa.Enum("sitting", "standing", "lying", "reclining", name="bodyposture"),
            nullable=True,
        ),
        sa.Column(
            "measurement_location",
            sa.Enum(
                "left_wrist",
                "right_wrist",
                "left_arm",
                "right_arm",
                name="measurementlocation",
            ),
            nullable=True,
        ),
        sa.Column("systolic_value", sa.Float(), nullable=False),
        sa.Column("diastolic_value", sa.Float(), nullable=False),
        sa.Column(
            "systolic_unit", sa.Enum("mmHg", name="bloodpressureunit"), nullable=True
        ),
        sa.Column(
            "diastolic_unit", sa.Enum("mmHg", name="bloodpressureunit"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "heartrate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column(
            "unit", sa.Enum("beats_per_min", name="heartrateunit"), nullable=True
        ),
        sa.Column("start_date_time", sa.DateTime(), nullable=False),
        sa.Column("end_date_time", sa.DateTime(), nullable=True),
        sa.Column(
            "descriptive_statistic",
            sa.Enum("average", "maximum", "minimum", name="descriptivestatistic"),
            nullable=True,
        ),
        sa.Column(
            "temporal_relationship_to_physical_activity",
            sa.Enum(
                "before_exercise",
                "after_exercise",
                "during_exercise",
                "at_rest",
                name="temporalrelationship",
            ),
            nullable=True,
        ),
        sa.Column(
            "temporal_relationship_to_sleep",
            sa.Enum(
                "before_sleep",
                "during_sleep",
                "after_sleep",
                name="temporalrelationshiptosleep",
            ),
            nullable=True,
        ),
        sa.Column(
            "body_posture",
            sa.Enum("sitting", "standing", "lying", "reclining", name="bodyposture"),
            nullable=True,
        ),
        sa.Column(
            "measurement_location",
            sa.Enum(
                "left_wrist",
                "right_wrist",
                "left_arm",
                "right_arm",
                name="measurementlocation",
            ),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "prescription",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("medication_name", sa.String(), nullable=False),
        sa.Column(
            "route",
            sa.Enum(
                "oral",
                "iv",
                "subcutaneous",
                "intramuscular",
                "transdermal",
                name="administrationroute",
            ),
            nullable=False,
        ),
        sa.Column("prescription_trigger", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "doseschedule",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("prescription_id", sa.Integer(), nullable=False),
        sa.Column("dose_duration_value", sa.Float(), nullable=True),
        sa.Column("dose_duration_unit", sa.String(), nullable=True),
        sa.Column("dose_administration_duration_value", sa.Float(), nullable=True),
        sa.Column("dose_administration_duration_unit", sa.String(), nullable=True),
        sa.Column("dose_value", sa.Float(), nullable=True),
        sa.Column("dose_unit", sa.String(), nullable=True),
        sa.Column("dose_min_value", sa.Float(), nullable=True),
        sa.Column("dose_max_value", sa.Float(), nullable=True),
        sa.Column("frequency", sa.String(), nullable=True),
        sa.Column("dose_prn_trigger", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["prescription_id"],
            ["prescription.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("doseschedule")
    op.drop_table("prescription")
    op.drop_table("heartrate")
    op.drop_table("bloodpressure")
    # ### end Alembic commands ###
