"""updated riskassesment model

Revision ID: e6b84ce95c35
Revises: 16f8bd47d3e7
Create Date: 2026-05-26 13:37:19.036164

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "e6b84ce95c35"
down_revision: Union[str, None] = "16f8bd47d3e7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "risk_assessment_result",
        sa.Column("disease", sa.String(length=255), nullable=False),
    )
    op.add_column(
        "risk_assessment_result", sa.Column("risk_score", sa.Float(), nullable=False)
    )
    op.add_column(
        "risk_assessment_result",
        sa.Column("risk_label", sa.String(length=100), nullable=False),
    )
    op.add_column(
        "risk_assessment_result",
        sa.Column(
            "predicted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.alter_column(
        "risk_assessment_result",
        "model_version",
        existing_type=sa.VARCHAR(length=50),
        nullable=False,
    )
    op.drop_constraint(
        "risk_assessment_result_profile_id_fkey",
        "risk_assessment_result",
        type_="foreignkey",
    )
    op.drop_column("risk_assessment_result", "inference_time_ms")
    op.drop_column("risk_assessment_result", "risk_level")
    op.drop_column("risk_assessment_result", "prediction_label")
    op.drop_column("risk_assessment_result", "model_name")
    op.drop_column("risk_assessment_result", "recommendation")
    op.drop_column("risk_assessment_result", "shap_values")
    op.drop_column("risk_assessment_result", "disease_type")
    op.drop_column("risk_assessment_result", "created_at")
    op.drop_column("risk_assessment_result", "risk_probability")
    op.drop_column("risk_assessment_result", "lime_explanation")
    op.drop_column("risk_assessment_result", "clinical_summary")
    op.drop_column("risk_assessment_result", "top_risk_factors")
    op.drop_column("risk_assessment_result", "profile_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "risk_assessment_result",
        sa.Column("profile_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "risk_assessment_result",
        sa.Column("top_risk_factors", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "risk_assessment_result",
        sa.Column("clinical_summary", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "risk_assessment_result",
        sa.Column("lime_explanation", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "risk_assessment_result",
        sa.Column(
            "risk_probability",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "risk_assessment_result",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "risk_assessment_result",
        sa.Column(
            "disease_type",
            postgresql.ENUM("CHD", "STROKE", "HYPERTENSION", "CVD", name="diseasetype"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "risk_assessment_result",
        sa.Column("shap_values", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "risk_assessment_result",
        sa.Column("recommendation", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "risk_assessment_result",
        sa.Column(
            "model_name", sa.VARCHAR(length=100), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "risk_assessment_result",
        sa.Column(
            "prediction_label", sa.BOOLEAN(), autoincrement=False, nullable=False
        ),
    )
    op.add_column(
        "risk_assessment_result",
        sa.Column(
            "risk_level",
            postgresql.ENUM("LOW", "MODERATE", "HIGH", "CRITICAL", name="risklevel"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "risk_assessment_result",
        sa.Column(
            "inference_time_ms",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_foreign_key(
        "risk_assessment_result_profile_id_fkey",
        "risk_assessment_result",
        "user_profile",
        ["profile_id"],
        ["id"],
    )
    op.alter_column(
        "risk_assessment_result",
        "model_version",
        existing_type=sa.VARCHAR(length=50),
        nullable=True,
    )
    op.drop_column("risk_assessment_result", "predicted_at")
    op.drop_column("risk_assessment_result", "risk_label")
    op.drop_column("risk_assessment_result", "risk_score")
    op.drop_column("risk_assessment_result", "disease")
    # ### end Alembic commands ###
