""" User user profile models

Revision ID: eb812596c210
Revises: 7ea068d30ded
Create Date: 2026-04-01 23:16:48.812147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "eb812596c210"
down_revision: Union[str, None] = "7ea068d30ded"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user_profile", sa.Column("first_name", sa.String(length=50), nullable=False)
    )
    op.add_column(
        "user_profile", sa.Column("middle_name", sa.String(length=50), nullable=True)
    )
    op.add_column(
        "user_profile", sa.Column("last_name", sa.String(length=50), nullable=False)
    )
    # -----------------------------
    # CREATE ENUM TYPES
    # -----------------------------
    smoking_enum = postgresql.ENUM(
        "never",
        "former",
        "passive",
        "current_light",
        "current_heavy",
        name="smokingstatus",
    )

    alcohol_enum = postgresql.ENUM("none", "moderate", "heavy", name="alcoholuse")

    smoking_enum.create(op.get_bind(), checkfirst=True)
    alcohol_enum.create(op.get_bind(), checkfirst=True)

    # -----------------------------
    # ADD COLUMNS
    # -----------------------------
    op.add_column("user_profile", sa.Column("smoking", smoking_enum, nullable=False))

    op.add_column("user_profile", sa.Column("alcohol_use", alcohol_enum, nullable=True))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user_profile", "smoking")
    op.drop_column("user_profile", "alcohol_use")

    smoking_enum = postgresql.ENUM(
        "never",
        "former",
        "passive",
        "current_light",
        "current_heavy",
        name="smokingstatus",
    )

    alcohol_enum = postgresql.ENUM("none", "moderate", "heavy", name="alcoholuse")

    smoking_enum.drop(op.get_bind(), checkfirst=True)
    alcohol_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_column("user_profile", "last_name")
    op.drop_column("user_profile", "middle_name")
    op.drop_column("user_profile", "first_name")
    # ### end Alembic commands ###
