"""add cigs_per_day to health assesment

Revision ID: f8675206707a
Revises: 60f2d44a0f17
Create Date: 2026-05-22 22:57:39.750984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "f8675206707a"
down_revision: Union[str, None] = "60f2d44a0f17"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "health_assessment", sa.Column("cigs_per_day", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("health_assessment", "cigs_per_day")
    # ### end Alembic commands ###
